name: "dishes"

services:
  db:
    image: postgres:13.5
    container_name: "dishes-postgres"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - database:/data/database

  nestjs_prod:
    container_name: "dishes-nestjs"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env


volumes:
  database:
